apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-app-deploy
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: skeletons/argocd 
    repoURL: https://github.com/${{ values.orgName }}/${{ values.repoName }}.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - CreateNamespace=true
