---
apiVersion: v1
kind: Service
namespace: demo-project
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${{ values.port }}
