---
apiVersion: route.openshift.io/v1
kind: Route
namespace: demo-project
metadata:
  name: springboot-route
spec:
  to:
    kind: Service
    name: springboot-service
  port:
    targetPort: ${{ values.port }}
