---
apiVersion: v1
kind: Service
namespace: ${{ values.namespace }}
metadata:
  name: springboot-service
spec:
  selector:
    app: ${{ values.projectName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${{ values.backendport }}
---
apiVersion: v1
kind: Service
namespace: ${{ values.namespace }}
metadata:
  name: react-app-service
spec:
  selector:
    app: ${{ values.projectName }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: ${{ values.frontendport }}
