---
apiVersion: v1
kind: Service
namespace: ${{ values.namespace }}
metadata:
  name: springboot-service
spec:
  selector:
    app: ${{ values.projectName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${{ values.port }}
