---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Spring Boot service
  tags:
    - java
    - springboot
  annotations:
    github.com/project-slug: ${{ values.repoUrl | parseRepoUrl }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
