---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.projectName }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.projectName }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.projectName }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.projectName }}
  template:
    metadata:
      labels:
        app: ${{ values.projectName }}
    spec:
      containers:
        - name: springboot
          image: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/${{ values.projectName }}-backend:latest
          ports:
            - containerPort: ${{ values.backendport }}
        - name: react-app
          image: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/${{ values.projectName }}-frontend:latest
          ports:
            - containerPort: ${{ values.frontendport }}
